#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Sep 21, 2020 11:25:46 AM CST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu {{}} -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 457x381+258+209
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1028 750
    wm minsize $top 116 1
    wm overrideredirect $top 0
    wm resizable $top 1 0
    wm deiconify $top
    wm title $top "IPERF3  UX"
    vTcl:DefineAlias "$top" "mainlevel" vTcl:Toplevel:WidgetProc "" 1
    labelframe $top.lab55 \
        -font TkDefaultFont -foreground black -text {Server Mode} \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 150 
    vTcl:DefineAlias "$top.lab55" "lframe_Server" vTcl:WidgetProc "mainlevel" 1
    set site_3_0 $top.lab55
    entry $site_3_0.ent57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent57" "entry_srvPort" vTcl:WidgetProc "mainlevel" 1
    bind $site_3_0.ent57 <<SetBalloon>> {
        set ::vTcl::balloon::%W {"Server port number must match with client port"}
    }
    entry $site_3_0.ent58 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent58" "entry_srvInterval" vTcl:WidgetProc "mainlevel" 1
    checkbutton $site_3_0.che59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Interval (s)} -variable che59 
    vTcl:DefineAlias "$site_3_0.che59" "chk_srvinterval" vTcl:WidgetProc "mainlevel" 1
    checkbutton $site_3_0.che50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Port -variable che50 
    vTcl:DefineAlias "$site_3_0.che50" "chk_srvPort" vTcl:WidgetProc "mainlevel" 1
    place $site_3_0.ent57 \
        -in $site_3_0 -x 99 -y 46 -width 44 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent58 \
        -in $site_3_0 -x 100 -y 23 -width 44 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che59 \
        -in $site_3_0 -x 10 -y 20 -anchor nw -bordermode ignore 
    place $site_3_0.che50 \
        -in $site_3_0 -x 6 -y 43 -width 62 -height 26 -anchor nw \
        -bordermode ignore 
    vTcl:copy_lock $top.lab55
    labelframe $top.lab43 \
        -font TkDefaultFont -foreground black -text {Client Mode} \
        -background $vTcl(actual_gui_bg) -height 255 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 180 
    vTcl:DefineAlias "$top.lab43" "lframe_ClientMode" vTcl:WidgetProc "mainlevel" 1
    set site_3_0 $top.lab43
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {IP address} 
    vTcl:DefineAlias "$site_3_0.lab45" "label_IP" vTcl:WidgetProc "mainlevel" 1
    entry $site_3_0.ent46 \
        -background white -disabledforeground #a3a3a3 \
        -font {-family {細明體} -size 8} -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent46" "entry_ipaddr" vTcl:WidgetProc "mainlevel" 1
    checkbutton $site_3_0.che47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -state disabled -text {Interval (s)} -variable che47 
    vTcl:DefineAlias "$site_3_0.che47" "chk_clientInterval" vTcl:WidgetProc "mainlevel" 1
    entry $site_3_0.ent48 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent48" "entry_cInterval" vTcl:WidgetProc "mainlevel" 1
    checkbutton $site_3_0.che49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Port -variable che49 
    vTcl:DefineAlias "$site_3_0.che49" "chk_cListenedPort" vTcl:WidgetProc "mainlevel" 1
    entry $site_3_0.ent50 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent50" "entry_cListenedPort" vTcl:WidgetProc "mainlevel" 1
    bind $site_3_0.ent50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {"Client port number must match with server port"}
    }
    checkbutton $site_3_0.che51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Test time (s)} -variable che51 
    vTcl:DefineAlias "$site_3_0.che51" "chk_testDuration" vTcl:WidgetProc "mainlevel" 1
    entry $site_3_0.ent52 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent52" "entry_testTime" vTcl:WidgetProc "mainlevel" 1
    checkbutton $site_3_0.che53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Number of  Parallel Client} -variable che53 
    vTcl:DefineAlias "$site_3_0.che53" "chk_numOfParallelClient" vTcl:WidgetProc "mainlevel" 1
    entry $site_3_0.ent55 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent55" "entry_numOfParallelClient" vTcl:WidgetProc "mainlevel" 1
    checkbutton $site_3_0.che56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Enable UDP} -variable che56 
    vTcl:DefineAlias "$site_3_0.che56" "chk_enableUDP" vTcl:WidgetProc "mainlevel" 1
    checkbutton $site_3_0.che63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text BandWidth -variable che63 
    vTcl:DefineAlias "$site_3_0.che63" "chk_bandwidth" vTcl:WidgetProc "mainlevel" 1
    entry $site_3_0.ent64 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent64" "entry_bw" vTcl:WidgetProc "mainlevel" 1
    ttk::combobox $site_3_0.tCo66 \
        -values 'KB','MB' -font TkTextFont -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo66" "combox_rate1" vTcl:WidgetProc "mainlevel" 1
    checkbutton $site_3_0.che68 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Window Size} -variable che68 
    vTcl:DefineAlias "$site_3_0.che68" "chk_windowSize" vTcl:WidgetProc "mainlevel" 1
    entry $site_3_0.ent71 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent71" "entry_windowSize" vTcl:WidgetProc "mainlevel" 1
    ttk::combobox $site_3_0.tCo72 \
        -values 'KB','MB' -font TkTextFont -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo72" "TCombobox1" vTcl:WidgetProc "mainlevel" 1
    place $site_3_0.lab45 \
        -in $site_3_0 -x 3 -y 20 -width 67 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 74 -y 21 -width 94 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che47 \
        -in $site_3_0 -x 3 -y 41 -width 92 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent48 \
        -in $site_3_0 -x 104 -y 44 -width 64 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che49 \
        -in $site_3_0 -x 5 -y 60 -width 51 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 105 -y 66 -width 64 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che51 \
        -in $site_3_0 -x 3 -y 81 -width 99 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent52 \
        -in $site_3_0 -x 104 -y 89 -width 64 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che53 \
        -in $site_3_0 -x 10 -y 103 -width 162 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent55 \
        -in $site_3_0 -x 27 -y 128 -width 84 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che56 \
        -in $site_3_0 -x 5 -y 145 -width 92 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che63 \
        -in $site_3_0 -x 5 -y 166 -width 92 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent64 \
        -in $site_3_0 -x 28 -y 188 -width 64 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo66 \
        -in $site_3_0 -x 100 -y 183 -width 53 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che68 \
        -in $site_3_0 -x 5 -y 205 -width 102 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent71 \
        -in $site_3_0 -x 28 -y 227 -width 64 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo72 \
        -in $site_3_0 -x 100 -y 226 -width 53 -relwidth 0 -height 22 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.lab43
    button $top.but51 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Start 
    vTcl:DefineAlias "$top.but51" "btn_Start" vTcl:WidgetProc "mainlevel" 1
    vTcl:copy_lock $top.but51
    button $top.but52 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Reset 
    vTcl:DefineAlias "$top.but52" "btn_Reset" vTcl:WidgetProc "mainlevel" 1
    vTcl:copy_lock $top.but52
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {iperf3 CMD} 
    vTcl:DefineAlias "$top.lab56" "label_iperfCmd" vTcl:WidgetProc "mainlevel" 1
    entry $top.ent57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -state readonly 
    vTcl:DefineAlias "$top.ent57" "entry_runCMD" vTcl:WidgetProc "mainlevel" 1
    bind $top.ent57 <<SetBalloon>> {
        set ::vTcl::balloon::%W {"Generate the iperf3 command automatically"}
    }
    vTcl:copy_lock $top.ent57
    labelframe $top.lab46 \
        -font TkDefaultFont -foreground black -relief flat -text Output \
        -background $vTcl(actual_gui_bg) -height 255 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 260 
    vTcl:DefineAlias "$top.lab46" "lframe_output" vTcl:WidgetProc "mainlevel" 1
    set site_3_0 $top.lab46
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr49 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_3_0.scr49" "scrolledtxt_output" vTcl:WidgetProc "mainlevel" 1

    $site_3_0.scr49.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    place $site_3_0.scr49 \
        -in $site_3_0 -x 4 -y 18 -width 251 -relwidth 0 -height 232 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.lab46
    button $top.but43 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Close 
    vTcl:DefineAlias "$top.but43" "btn_Close" vTcl:WidgetProc "mainlevel" 1
    vTcl:copy_lock $top.but43
    radiobutton $top.rad45 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Server -value 1 
    vTcl:DefineAlias "$top.rad45" "radiobtn_server" vTcl:WidgetProc "mainlevel" 1
    vTcl:copy_lock $top.rad45
    radiobutton $top.rad46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text Client -value 2 
    vTcl:DefineAlias "$top.rad46" "radiobtn_client" vTcl:WidgetProc "mainlevel" 1
    vTcl:copy_lock $top.rad46
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab55 \
        -in $top -x 97 -y 0 -width 150 -relwidth 0 -height 75 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 6 -y 76 -width 180 -relwidth 0 -height 255 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but51 \
        -in $top -x 360 -y 10 -width 78 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 260 -y 10 -width 78 -relwidth 0 -height 66 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -y 330 -width 107 -relwidth 0 -height 22 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 7 -y 350 -width 174 -relwidth 0 -height 17 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 190 -y 75 -width 260 -relwidth 0 -height 255 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but43 \
        -in $top -x 201 -y 337 -width 78 -relwidth 0 -height 36 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.rad45 \
        -in $top -x 14 -y 10 -width 62 -height 26 -anchor nw \
        -bordermode ignore 
    place $top.rad46 \
        -in $top -x 14 -y 40 -width 62 -height 26 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

